### ISSUE TITLE
Unsafety detected on virustotal for windows binary

### ISSUE THREAD

**Issue by c33s** [moldabekov/virusgotal#12]
- Acronis: Suspicious
- SecureAge APEX: Malicious
- CrowdStrike Falcon: Win/malicious_confidence_60% (W)
- McAfee-GW-Edition: BehavesLike.Win64.CoinMiner.vc

https://www.virustotal.com/gui/file/4e7351d906826a6e29e5c1ee1fdbd3429070f4b5c027b5b4927e95017038cf52/detection

**Comment by moldabekov** [comment]
@c33s thx Julian. Source code is open, you can make an audit to ensure that this project doesn't contain malicious parts.

**Comment by c33s** [comment]
>  Source code is open, you can make an audit to ensure that this project doesn't contain malicious parts.
i know

i just wanted you to know that four engines found "something".

maybe you want to report it to the av engines developers as false positive or maybe you want to adapt your code (looks better if a software that uses and promotes virustotal has not 4 warnings on virustotal 😄 ).

feel free to close.

**Comment by moldabekov** [comment]
@c33s thanks for contribution mate :) I really appreciate it.

To be honest I don't give a heck about software which wants to look like a legit AV :) I had a broad experience with CrowdStrike, and all I can say about it could fit in one picture:


![EDR](https://user-images.githubusercontent.com/669547/99149414-c86ca000-2685-11eb-8a84-b7f4abdc1af8.jpg)
