### ISSUE TITLE
"virusgotal-windows-amd64.exe" detected by VirusTotal scanners

### ISSUE THREAD

**Issue by Akh-bar** [moldabekov/virusgotal#13]
Several VirusTotal engines detect malware in "virusgotal-windows-amd64.exe":
https://www.virustotal.com/gui/file/4e7351d906826a6e29e5c1ee1fdbd3429070f4b5c027b5b4927e95017038cf52/detection

**Comment by moldabekov** [comment]
It is due to UPX compression. You can check it by compiling `virusgotal` by yourself and compressing it with `upx -9`
